### PR TITLE
docs: Add a method to the Readme file - ask_question()

### PR DESCRIPTION
**Pull request by CyrilBaah**
Description
Add a method **ask_question()** to README.md and how it can be used

Change Type
It is a documentation update

### CODE REVIEW

**Review by mason-at-pieces — CHANGES_REQUESTED** [review]
@CyrilBaah great catch!

Thinking about this, could we make the methods be in the following order on this readme?

1. `ask_question(question)`
2. `create_conversation(name=None, first_message=None)`
3. `prompt_conversation(question, conversation_id, regenerate_conversation_name=False)`
4. `get_conversation(conversation_id, include_raw_messages=False)`
5. `update_conversation_name(conversation_id)`
6. `get_conversations()`
7. `get_user_profile_picture()`

**Comment by CyrilBaah** [comment]
Yes, would update to reflect the new order

**Review by CyrilBaah — COMMENTED** [review]
Description
Refactor readme to be in following [order](https://github.com/mason-at-pieces/pieces-copilot-python-sdk/pull/6#pullrequestreview-2231879854)

Change Type
It is a documentation update

**Review by shivaypiece — APPROVED** [review]

**Review by mason-at-pieces — APPROVED** [review]
lgtm

**Pull request merged**
